<template>
	<div class="xl:flex xl:justify-between">
		<button type="button" class="inline-block bg-gray-700 text-lg hover:bg-gray-800 focus:bg-gray-800 text-white font-semibold focus:outline-none focus:shadow-outline leading-tight rounded select-none align-middle whitespace-no-wrap px-3 py-2 mb-2 mr-2 cursor-pointer">Submit</button>
		<button type="button" class="inline-block bg-red-700 text-lg hover:bg-red-800 focus:bg-red-800 text-white font-semibold focus:outline-none focus:shadow-outline leading-tight rounded select-none align-middle whitespace-no-wrap px-3 py-2 mb-2 mr-2 cursor-pointer">Submit</button>
		<button type="button" class="inline-block bg-orange-700 text-lg hover:bg-orange-800 focus:bg-orange-800 text-white font-semibold focus:outline-none focus:shadow-outline leading-tight rounded select-none align-middle whitespace-no-wrap px-3 py-2 mb-2 mr-2 cursor-pointer">Submit</button>
		<button type="button" class="inline-block bg-yellow-700 text-lg hover:bg-yellow-800 focus:bg-yellow-800 text-white font-semibold focus:outline-none focus:shadow-outline leading-tight rounded select-none align-middle whitespace-no-wrap px-3 py-2 mb-2 mr-2 cursor-pointer">Submit</button>
		<button type="button" class="inline-block bg-green-700 text-lg hover:bg-green-800 focus:bg-green-800 text-white font-semibold focus:outline-none focus:shadow-outline leading-tight rounded select-none align-middle whitespace-no-wrap px-3 py-2 mb-2 mr-2 cursor-pointer">Submit</button>
		<button type="button" class="inline-block bg-teal-700 text-lg hover:bg-teal-800 focus:bg-teal-800 text-white font-semibold focus:outline-none focus:shadow-outline leading-tight rounded select-none align-middle whitespace-no-wrap px-3 py-2 mb-2 mr-2 cursor-pointer">Submit</button>
		<button type="button" class="inline-block bg-blue-700 text-lg hover:bg-blue-800 focus:bg-blue-800 text-white font-semibold focus:outline-none focus:shadow-outline leading-tight rounded select-none align-middle whitespace-no-wrap px-3 py-2 mb-2 mr-2 cursor-pointer">Submit</button>
		<button type="button" class="inline-block bg-indigo-700 text-lg hover:bg-indigo-800 focus:bg-indigo-800 text-white font-semibold focus:outline-none focus:shadow-outline leading-tight rounded select-none align-middle whitespace-no-wrap px-3 py-2 mb-2 mr-2 cursor-pointer">Submit</button>
		<button type="button" class="inline-block bg-purple-700 text-lg hover:bg-purple-800 focus:bg-purple-800 text-white font-semibold focus:outline-none focus:shadow-outline leading-tight rounded select-none align-middle whitespace-no-wrap px-3 py-2 mb-2 mr-2 cursor-pointer">Submit</button>
		<button type="button" class="inline-block bg-pink-700 text-lg hover:bg-pink-800 focus:bg-pink-800 text-white font-semibold focus:outline-none focus:shadow-outline leading-tight rounded select-none align-middle whitespace-no-wrap px-3 py-2 mb-2 mr-2 cursor-pointer">Submit</button>
	</div>
</template>